name: genDiff check
run-name: ${{ github.actor }} is testing out gendiff.js ✨
on: [push]
jobs:
  gendiff-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lauching $GITHUB_WORKFLOW"
      - name: Check out the repository to the runner
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Launch test
        run: make test
      - name: Launch linter
        run: npx eslint .
  
